@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNmYmMwYWUwLWNjZGEtNDRjMS05YmQyLWQzMzUxY2ZlM2IzZiIsImVtYWlsIjoibGF5QHNoYXcuY29tIiwiaWF0IjoxNjU3NTUwMTY0LCJleHAiOjE2NTc5ODIxNjR9.oLrk8MEkR2eKo8okD_3puW824v1le-pfmmWaefl7rZc


###
POST http://localhost:3003/user/signup 
Content-Type: application/json 

{
    "name": "Layane Bastos",
    "email": "lay@shaw.com",
    "password": "123456"
}

###

POST http://localhost:3003/user/login 
Content-Type: application/json 

{
    "email": "lay@shaw.com",
    "password": "123456"
}

### 
POST http://localhost:3003/post/create 
Content-Type: application/json 
Authorization: {{token}}

{
    "photo": "link",
    "description": "viva a vida",
    "type": "NORMAL"
}

###

GET http://localhost:3003/post/69b61e29-ac18-4b32-819c-18e7f86cf60f
Authorization: {{token}}