@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzMzE4MTRmLTYxMTMtNDA0YS05ODkyLTNlNDVlYmVkODlmZCIsImVtYWlsIjoicm9kcmlnbzEyQGVtYWlsLmNvbSIsImlhdCI6MTY1NzUzNjMwMywiZXhwIjoxNjU3OTY4MzAzfQ.Z4IgskZuEpzZ5wq8ixQUFkce7251a-GaIzjOYIxXsk0


###
POST http://localhost:3003/user/signup 
Content-Type: application/json 

{
    "name": 2,
    "email": "rodrigo12@email.com",
    "password": "1223145153"
}

###

POST http://localhost:3003/user/login 
Content-Type: application/json 

{
    "email": "rodrigo12@email.c",
    "password": "1223145153"
}
###
DELETE http://localhost:3003/


### 
POST http://localhost:3003/post/create 
Content-Type: application/json 
Authorization: {{token}}

{
    "photo": "link",
    "description": "viva a vida",
    "createdAt": "2022-07-11",
    "type": "NORMAL"
}

###

GET http://localhost:3003/post/69b61e29-ac18-4b32-819c-18e7f86cf60f
Authorization: {{token}}