GET http://localhost:3003/

###
POST http://localhost:3003/form/send
Content-Type: application/json

{
   "firstName": "Layane", 
   "lastName": "Bastos", 
   "participation": 23
}

###
DELETE http://localhost:3003/